[package]
name = "skyline"
version = "0.1.0"
authors = ["jam1garner <jam1.mcleod@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skyline_macro = { path = "./skyline_macro" }
nnsdk = { git = "https://github.com/ultimate-research/nnsdk-rs.git" }
libc-nnsdk = { git = "https://github.com/ultimate-research/libc-nnsdk.git" }

[features]
default = ["std"]
std = []
nro_internal = []
